#include "schema.h"

const char *DB_SCHEMA =
    "PRAGMA foreign_keys = ON;"

    "CREATE TABLE IF NOT EXISTS subjects ("
    "    id    INTEGER PRIMARY KEY AUTOINCREMENT,"
    "    name  TEXT"
    ");"

    "CREATE TABLE IF NOT EXISTS daily_log ("
    "    date             TEXT PRIMARY KEY,"
    "    sleep_time       INTEGER,"
    "    wake_time        INTEGER,"
    "    sleep_dur_min    INTEGER,"
    "    sleep_quality    INTEGER,"
    "    mood             INTEGER,"
    "    energy           INTEGER,"
    "    eat_out_meals    INTEGER,"
    "    home_cooked      INTEGER,"
    "    steps            INTEGER,"
    "    outside_min      INTEGER,"
    "    screen_time_min  INTEGER,"
    "    exercise         INTEGER,"
    "    caffeine_drinks  INTEGER,"
    "    stress           INTEGER,"
    "    productive_feel  INTEGER,"
    "    notes            TEXT"
    ");"

    "CREATE TABLE IF NOT EXISTS study_sessions ("
    "    id                INTEGER PRIMARY KEY AUTOINCREMENT,"
    "    date              TEXT,"
    "    start_time        INTEGER,"
    "    end_time          INTEGER,"
    "    duration_min      INTEGER,"
    "    mood_before       INTEGER,"
    "    mood_after        INTEGER,"
    "    energy_before     INTEGER,"
    "    focus_rating      INTEGER,"
    "    subject           INTEGER REFERENCES subjects(id),"
    "    environment       INTEGER,"
    "    distraction_count INTEGER,"
    "    notes             TEXT"
    ");"

    "CREATE TABLE IF NOT EXISTS expenses ("
    "    id               INTEGER PRIMARY KEY AUTOINCREMENT,"
    "    date             TEXT,"
    "    category         INTEGER,"
    "    amount_cents     INTEGER,"
    "    need_score       INTEGER,"
    "    want_score       INTEGER,"
    "    importance       REAL,"
    "    recurrence       INTEGER,"
    "    planned          INTEGER,"
    "    payment_method   INTEGER,"
    "    time_of_purchase INTEGER,"
    "    notes            TEXT"
    ");"

    "CREATE TABLE IF NOT EXISTS bank_snapshots ("
    "    date              TEXT PRIMARY KEY,"
    "    balance_cents     INTEGER,"
    "    computed_cents    INTEGER,"
    "    discrepancy_cents INTEGER"
    ");"

    "CREATE TABLE IF NOT EXISTS income_events ("
    "    id           INTEGER PRIMARY KEY AUTOINCREMENT,"
    "    date         TEXT,"
    "    amount_cents INTEGER,"
    "    source       INTEGER,"
    "    notes        TEXT"
    ");";

const char* insert_daily_log = "INSERT INTO daily_log ("
        "    date, sleep_time, wake_time, sleep_dur_min, sleep_quality, "
        "    mood, energy, eat_out_meals, home_cooked, steps, "
        "    outside_min, screen_time_min, exercise, caffeine_drinks, "
        "    stress, productive_feel, notes"
        ") VALUES ("
        "    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

const char* first_log = "INSERT INTO daily_log (date, sleep_time, wake_time, sleep_quality, mood, energy) "
        "VALUES (date('now', 'localtime'), ?, ?, ?, ?, ?);";

const char* first_bank_balance = "INSERT INTO bank_snapshots (date, balance_cents, computed_cents, discrepancy_cents) "
        "VALUES (date('now', 'localtime'), ?, ?, 0);";

const char* insert_subjects = "INSERT INTO subjects (name) VALUES (?);";
